import { createFileRoute, useNavigate } from '@tanstack/react-router';
import { useState, useEffect } from 'react';
import { toast } from 'sonner';
import { Label } from '@workspace/ui/components/label';
import { Input } from '@workspace/ui/components/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@workspace/ui/components/select';
import { Button } from '@workspace/ui/components/button';
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from '@workspace/ui/components/collapsible';
import { CaretDown } from '@phosphor-icons/react';
import {
  REGIONS, SIZES, MODELS,
  REGION_LABELS, SIZE_LABELS, MODEL_LABELS,
  validateDeploymentName,
  generateDeploymentName,
} from '../../../lib/validation';
import { PersonaPicker } from '../../../components/deploy-wizard/persona-picker';
import type { SelectedPersona } from '../../../components/deploy-wizard/persona-picker';
import { createDeployment } from '../../../lib/server/deployments';

export const Route = createFileRoute('/_authenticated/deploy/')({
  component: DeployPage,
});

function DeployPage() {
  const navigate = useNavigate();
  const [name, setName] = useState('');
  const [isNameAutoGenerated, setIsNameAutoGenerated] = useState(true);
  const [region, setRegion] = useState('nyc1');
  const [size, setSize] = useState('s-2vcpu-4gb');
  const [primaryModel, setPrimaryModel] = useState('anthropic');
  const [persona, setPersona] = useState<SelectedPersona | null>(null);
  const [nameError, setNameError] = useState<string | null>(null);
  const [deploying, setDeploying] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [advancedOpen, setAdvancedOpen] = useState(false);

  // Auto-generate name on mount
  useEffect(() => {
    setName(generateDeploymentName());
  }, []);

  const handlePersonaSelect = (selected: SelectedPersona | null) => {
    setPersona(selected);
    if (isNameAutoGenerated) {
      setName(generateDeploymentName(selected?.slug));
      setNameError(null);
    }
  };

  const handleNameChange = (value: string) => {
    setName(value);
    setIsNameAutoGenerated(false);
    setNameError(null);
  };

  const handleDeploy = async () => {
    const validation = validateDeploymentName(name);
    if (!validation.valid) {
      setNameError(validation.error ?? 'Invalid name');
      return;
    }
    if (deploying) return;
    setDeploying(true);
    setError(null);
    try {
      const result = await createDeployment({
        data: {
          name,
          region,
          size,
          primaryModel,
          personaSlug: persona?.slug,
          personaName: persona?.name,
        },
      });
      toast.success(`Agent "${name}" is deploying!`);
      navigate({ to: '/deployments/$deploymentId', params: { deploymentId: result.deploymentId } });
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Deployment failed. Please try again.');
      setDeploying(false);
    }
  };

  const isValid = name && !nameError && region && size && primaryModel;

  return (
    <div className="space-y-8">
      {/* Persona Picker — hero section */}
      <section>
        <Label className="text-base font-medium mb-3 block">Choose a Persona</Label>
        <PersonaPicker
          mode="inline"
          selectedSlug={persona?.slug}
          onSelect={handlePersonaSelect}
          disabled={deploying}
        />
      </section>

      {/* Deployment Name */}
      <div className="space-y-2">
        <Label htmlFor="name">Deployment Name</Label>
        <Input
          id="name"
          placeholder="my-agent"
          value={name}
          onChange={(e) => handleNameChange(e.target.value)}
          onBlur={() => {
            const v = validateDeploymentName(name);
            setNameError(v.valid ? null : (v.error ?? 'Invalid'));
          }}
          disabled={deploying}
        />
        {nameError && <p className="text-sm text-red-600">{nameError}</p>}
        <p className="text-xs text-muted-foreground">Lowercase letters, numbers, and hyphens. 3-63 characters.</p>
      </div>

      {/* Advanced Settings */}
      <Collapsible open={advancedOpen} onOpenChange={setAdvancedOpen}>
        <CollapsibleTrigger asChild>
          <button
            type="button"
            className="flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground transition-colors"
          >
            <CaretDown
              className={`h-4 w-4 transition-transform ${advancedOpen ? 'rotate-180' : ''}`}
            />
            Advanced Settings
          </button>
        </CollapsibleTrigger>
        <CollapsibleContent>
          <div className="space-y-4 pt-4 pl-6 border-l-2 border-border ml-2">
            <div className="space-y-2">
              <Label>Region</Label>
              <Select value={region} onValueChange={setRegion} disabled={deploying}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {REGIONS.map((r) => (
                    <SelectItem key={r} value={r}>
                      {REGION_LABELS[r] ?? r}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label>Size</Label>
              <Select value={size} onValueChange={setSize} disabled={deploying}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {SIZES.map((s) => (
                    <SelectItem key={s} value={s}>
                      {SIZE_LABELS[s] ?? s}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label>Primary AI Model</Label>
              <Select value={primaryModel} onValueChange={setPrimaryModel} disabled={deploying}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {MODELS.map((m) => (
                    <SelectItem key={m} value={m}>
                      {MODEL_LABELS[m] ?? m}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
        </CollapsibleContent>
      </Collapsible>

      {/* Error */}
      {error && (
        <div className="rounded-md bg-red-50 border border-red-200 p-3 text-sm text-red-700">
          {error}
        </div>
      )}

      {/* Deploy button */}
      <Button
        onClick={handleDeploy}
        disabled={!isValid || deploying}
        className="w-full"
        size="lg"
      >
        {deploying ? 'Deploying...' : 'Deploy Agent'}
      </Button>
    </div>
  );
}
