import { createFileRoute, useNavigate } from '@tanstack/react-router';
import { useState, useEffect } from 'react';
import { toast } from 'sonner';
import { Label } from '@workspace/ui/components/label';
import { Input } from '@workspace/ui/components/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@workspace/ui/components/select';
import { Button } from '@workspace/ui/components/button';
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from '@workspace/ui/components/collapsible';
import { CaretDown } from '@phosphor-icons/react';
import {
  REGIONS, SIZES, SUPPORTED_PROVIDERS,
  REGION_LABELS, SIZE_LABELS, PROVIDER_LABELS,
  validateDeploymentName,
  generateDeploymentName,
} from '../../../lib/validation';
import { PersonaPicker } from '../../../components/deploy-wizard/persona-picker';
import type { SelectedPersona } from '../../../components/deploy-wizard/persona-picker';
import { createDeployment } from '../../../lib/server/deployments';
import { getMarketplaceTemplateBySlug } from '../../../lib/server/marketplace';
import type { MarketplaceTemplate } from '../../../lib/server/marketplace';

export const Route = createFileRoute('/_authenticated/deploy/')({
  component: DeployPage,
  validateSearch: (search: Record<string, unknown>) => ({
    template: typeof search.template === 'string' ? search.template : undefined,
    provider: typeof search.provider === 'string' ? search.provider : undefined,
  }),
});

function DeployPage() {
  const navigate = useNavigate();
  const { template: templateSlug, provider: urlProvider } = Route.useSearch();
  const [name, setName] = useState('');
  const [isNameAutoGenerated, setIsNameAutoGenerated] = useState(true);
  const [region, setRegion] = useState('sgp1');
  const [size, setSize] = useState('s-2vcpu-4gb');
  const [provider, setProvider] = useState(
    urlProvider && SUPPORTED_PROVIDERS.includes(urlProvider)
      ? urlProvider
      : 'digitalocean',
  );
  const [persona, setPersona] = useState<SelectedPersona | null>(null);
  const [templateData, setTemplateData] = useState<MarketplaceTemplate | null>(null);
  const [nameError, setNameError] = useState<string | null>(null);
  const [deploying, setDeploying] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [advancedOpen, setAdvancedOpen] = useState(false);

  // Auto-generate name on mount
  useEffect(() => {
    setName(generateDeploymentName());
  }, []);

  // Pre-fill from URL template slug
  useEffect(() => {
    if (!templateSlug) return;
    let cancelled = false;

    getMarketplaceTemplateBySlug({ data: { slug: templateSlug } })
      .then((tmpl) => {
        if (cancelled || !tmpl) {
          if (!cancelled && !tmpl) {
            toast.warning(`Template "${templateSlug}" not found. You can deploy manually.`);
          }
          return;
        }
        setTemplateData(tmpl);
        const selected: SelectedPersona = {
          slug: tmpl.slug,
          name: tmpl.name,
          templateId: tmpl.id,
          providerSnapshots: tmpl.provider_snapshots,
        };
        setPersona(selected);
        if (isNameAutoGenerated) {
          setName(generateDeploymentName(tmpl.slug));
          setNameError(null);
        }
      })
      .catch(() => {
        if (!cancelled) {
          toast.warning(`Could not load template "${templateSlug}". You can deploy manually.`);
        }
      });

    return () => { cancelled = true; };
  }, [templateSlug]); // eslint-disable-line react-hooks/exhaustive-deps

  const handlePersonaSelect = (selected: SelectedPersona | null) => {
    setPersona(selected);
    // Clear template data when user manually picks a different persona
    if (selected?.slug !== templateData?.slug) {
      setTemplateData(null);
    }
    if (isNameAutoGenerated) {
      setName(generateDeploymentName(selected?.slug));
      setNameError(null);
    }
  };

  const handleNameChange = (value: string) => {
    setName(value);
    setIsNameAutoGenerated(false);
    setNameError(null);
  };

  const handleDeploy = async () => {
    const validation = validateDeploymentName(name);
    if (!validation.valid) {
      setNameError(validation.error ?? 'Invalid name');
      return;
    }
    if (deploying) return;
    setDeploying(true);
    setError(null);
    try {
      // Resolve snapshot name from template's provider_snapshots JSONB
      const resolvedTemplateId = templateData?.id ?? persona?.templateId;
      const providerSnaps = templateData?.provider_snapshots ?? persona?.providerSnapshots;
      const resolvedSnapshotName = providerSnaps?.[provider] ?? undefined;

      const result = await createDeployment({
        data: {
          name,
          region,
          size,
          personaSlug: persona?.slug,
          personaName: persona?.name,
          snapshotName: resolvedSnapshotName,
          templateId: resolvedTemplateId,
          provider,
        },
      });
      toast.success(`Agent "${name}" is deploying!`);
      navigate({ to: '/deployments/$deploymentId', params: { deploymentId: result.deploymentId } });
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Deployment failed. Please try again.');
      setDeploying(false);
    }
  };

  const isValid = name && !nameError && region && size;

  return (
    <div className="space-y-8">
      {/* Persona Picker — hero section */}
      <section>
        <Label className="text-base font-medium mb-3 block">Choose a Persona</Label>
        <PersonaPicker
          mode="inline"
          selectedSlug={persona?.slug}
          onSelect={handlePersonaSelect}
          disabled={deploying}
        />
      </section>

      {/* Deployment Name */}
      <div className="space-y-2">
        <Label htmlFor="name">Deployment Name</Label>
        <Input
          id="name"
          placeholder="my-agent"
          value={name}
          onChange={(e) => handleNameChange(e.target.value)}
          onBlur={() => {
            const v = validateDeploymentName(name);
            setNameError(v.valid ? null : (v.error ?? 'Invalid'));
          }}
          disabled={deploying}
        />
        {nameError && <p className="text-sm text-red-600">{nameError}</p>}
        <p className="text-xs text-muted-foreground">Lowercase letters, numbers, and hyphens. 3-63 characters.</p>
      </div>

      {/* Provider Selector */}
      <div className="space-y-2">
        <Label>Provider</Label>
        <Select value={provider} onValueChange={setProvider} disabled={deploying}>
          <SelectTrigger>
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {SUPPORTED_PROVIDERS.map((p) => (
              <SelectItem key={p} value={p}>
                {PROVIDER_LABELS[p] ?? p}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      {/* Advanced Settings */}
      <Collapsible open={advancedOpen} onOpenChange={setAdvancedOpen}>
        <CollapsibleTrigger asChild>
          <button
            type="button"
            className="flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground transition-colors"
          >
            <CaretDown
              className={`h-4 w-4 transition-transform ${advancedOpen ? 'rotate-180' : ''}`}
            />
            Advanced Settings
          </button>
        </CollapsibleTrigger>
        <CollapsibleContent>
          <div className="space-y-4 pt-4 pl-6 border-l-2 border-border ml-2">
            <div className="space-y-2">
              <Label>Region</Label>
              <Select value={region} onValueChange={setRegion} disabled={deploying}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {REGIONS.map((r) => (
                    <SelectItem key={r} value={r}>
                      {REGION_LABELS[r] ?? r}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label>Size</Label>
              <Select value={size} onValueChange={setSize} disabled={deploying}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {SIZES.map((s) => (
                    <SelectItem key={s} value={s}>
                      {SIZE_LABELS[s] ?? s}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

          </div>
        </CollapsibleContent>
      </Collapsible>

      {/* Error */}
      {error && (
        <div className="rounded-md bg-red-50 border border-red-200 p-3 text-sm text-red-700">
          {error}
        </div>
      )}

      {/* Deploy button */}
      <Button
        onClick={handleDeploy}
        disabled={!isValid || deploying}
        className="w-full"
        size="lg"
      >
        {deploying ? (
          <span className="flex items-center justify-center gap-2">
            <span className="h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent" />
            Deploying...
          </span>
        ) : 'Deploy Agent'}
      </Button>
      {deploying && (
        <p className="text-center text-sm text-muted-foreground animate-pulse">
          Setting up your agent. You'll be redirected once provisioning starts...
        </p>
      )}
    </div>
  );
}
