/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDeployRouteImport } from './routes/_authenticated/deploy'
import { Route as AuthenticatedDeployIndexRouteImport } from './routes/_authenticated/deploy/index'
import { Route as AuthenticatedDeployReviewRouteImport } from './routes/_authenticated/deploy/review'
import { Route as AuthenticatedDeploymentsDeploymentIdRouteImport } from './routes/_authenticated/deployments/$deploymentId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDeployRoute = AuthenticatedDeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDeployIndexRoute = AuthenticatedDeployIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedDeployRoute,
} as any)
const AuthenticatedDeployReviewRoute = AuthenticatedDeployReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedDeployRoute,
} as any)
const AuthenticatedDeploymentsDeploymentIdRoute = AuthenticatedDeploymentsDeploymentIdRouteImport.update({
  id: '/deployments/$deploymentId',
  path: '/deployments/$deploymentId',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/deploy': typeof AuthenticatedDeployRouteWithChildren
  '/deploy/': typeof AuthenticatedDeployIndexRoute
  '/deploy/review': typeof AuthenticatedDeployReviewRoute
  '/deployments/$deploymentId': typeof AuthenticatedDeploymentsDeploymentIdRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/deploy': typeof AuthenticatedDeployIndexRoute
  '/deploy/review': typeof AuthenticatedDeployReviewRoute
  '/deployments/$deploymentId': typeof AuthenticatedDeploymentsDeploymentIdRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/deploy': typeof AuthenticatedDeployRouteWithChildren
  '/_authenticated/deploy/': typeof AuthenticatedDeployIndexRoute
  '/_authenticated/deploy/review': typeof AuthenticatedDeployReviewRoute
  '/_authenticated/deployments/$deploymentId': typeof AuthenticatedDeploymentsDeploymentIdRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/dashboard' | '/settings' | '/deploy' | '/deploy/' | '/deploy/review' | '/deployments/$deploymentId' | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/dashboard' | '/settings' | '/deploy' | '/deploy/review' | '/deployments/$deploymentId' | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/deploy'
    | '/_authenticated/deploy/'
    | '/_authenticated/deploy/review'
    | '/_authenticated/deployments/$deploymentId'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deploy': {
      id: '/_authenticated/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof AuthenticatedDeployRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deploy/': {
      id: '/_authenticated/deploy/'
      path: '/'
      fullPath: '/deploy/'
      preLoaderRoute: typeof AuthenticatedDeployIndexRouteImport
      parentRoute: typeof AuthenticatedDeployRoute
    }
    '/_authenticated/deploy/review': {
      id: '/_authenticated/deploy/review'
      path: '/review'
      fullPath: '/deploy/review'
      preLoaderRoute: typeof AuthenticatedDeployReviewRouteImport
      parentRoute: typeof AuthenticatedDeployRoute
    }
    '/_authenticated/deployments/$deploymentId': {
      id: '/_authenticated/deployments/$deploymentId'
      path: '/deployments/$deploymentId'
      fullPath: '/deployments/$deploymentId'
      preLoaderRoute: typeof AuthenticatedDeploymentsDeploymentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedDeployRouteChildren {
  AuthenticatedDeployIndexRoute: typeof AuthenticatedDeployIndexRoute
  AuthenticatedDeployReviewRoute: typeof AuthenticatedDeployReviewRoute
}

const AuthenticatedDeployRouteChildren: AuthenticatedDeployRouteChildren = {
  AuthenticatedDeployIndexRoute: AuthenticatedDeployIndexRoute,
  AuthenticatedDeployReviewRoute: AuthenticatedDeployReviewRoute,
}

const AuthenticatedDeployRouteWithChildren = AuthenticatedDeployRoute._addFileChildren(
  AuthenticatedDeployRouteChildren,
)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedDeployRoute: typeof AuthenticatedDeployRouteWithChildren
  AuthenticatedDeploymentsDeploymentIdRoute: typeof AuthenticatedDeploymentsDeploymentIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedDeployRoute: AuthenticatedDeployRouteWithChildren,
  AuthenticatedDeploymentsDeploymentIdRoute: AuthenticatedDeploymentsDeploymentIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
