import { createFileRoute, Link } from '@tanstack/react-router';
import { useState, useEffect } from 'react';
import { Label } from '@workspace/ui/components/label';
import { Input } from '@workspace/ui/components/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@workspace/ui/components/select';
import { Button } from '@workspace/ui/components/button';
import {
  REGIONS,
  SIZES,
  REGION_LABELS,
  SIZE_LABELS,
  generateDeploymentName,
  validateDeploymentName,
} from '../../lib/validation';
import { listAgentTemplates } from '../../lib/server/agent-templates';
import type { AgentTemplate } from '../../lib/server/agent-templates';
import { useRestoreMutation } from '../../hooks/useSnapshotMutation';
import { OperationProgressBar } from '../../components/operation-progress-bar';
import { updateDeploymentAfterRestore } from '../../lib/server/deployments';

export const Route = createFileRoute('/_authenticated/restore')({
  component: RestorePage,
});

interface SnapshotOption {
  templateId: string;
  templateName: string;
  snapshotName: string;
}

function RestorePage() {
  const [name, setName] = useState('');
  const [isNameAutoGenerated, setIsNameAutoGenerated] = useState(true);
  const [nameError, setNameError] = useState<string | null>(null);
  const [snapshot, setSnapshot] = useState('');
  const [region, setRegion] = useState('sgp1');
  const [size, setSize] = useState('s-2vcpu-4gb');
  const [error, setError] = useState<string | null>(null);

  // Snapshot loading state
  const [snapshots, setSnapshots] = useState<SnapshotOption[]>([]);
  const [loadingSnapshots, setLoadingSnapshots] = useState(true);
  const [snapshotError, setSnapshotError] = useState<string | null>(null);

  // Restore mutation
  const {
    mutate,
    isPending: restoring,
    mutationError,
    progress,
    deploymentId,
    reset: resetMutation,
  } = useRestoreMutation();
  const [startedAt, setStartedAt] = useState<number | null>(null);

  // Auto-generate name on mount
  useEffect(() => {
    setName(generateDeploymentName());
  }, []);

  // Load snapshots from agent_templates
  useEffect(() => {
    let cancelled = false;

    setLoadingSnapshots(true);
    setSnapshotError(null);

    listAgentTemplates({ data: {} })
      .then((result) => {
        if (cancelled) return;

        const options: SnapshotOption[] = [];
        for (const template of result.data) {
          const doSnapshot = extractDigitalOceanSnapshot(template);
          if (doSnapshot) {
            options.push({
              templateId: template.id,
              templateName: template.name,
              snapshotName: doSnapshot,
            });
          }
        }
        setSnapshots(options);
      })
      .catch((err) => {
        if (cancelled) return;
        setSnapshotError(
          err instanceof Error ? err.message : 'Failed to load snapshots'
        );
      })
      .finally(() => {
        if (!cancelled) setLoadingSnapshots(false);
      });

    return () => {
      cancelled = true;
    };
  }, []);

  const handleNameChange = (value: string) => {
    setName(value);
    setIsNameAutoGenerated(false);
    setNameError(null);
  };

  const handleSnapshotChange = (value: string) => {
    setSnapshot(value);
    if (isNameAutoGenerated) {
      const selected = snapshots.find((s) => s.snapshotName === value);
      if (selected) {
        setName(generateDeploymentName(selected.templateName.toLowerCase().replace(/\s+/g, '-')));
        setNameError(null);
      }
    }
  };

  const handleRestore = async () => {
    const validation = validateDeploymentName(name);
    if (!validation.valid) {
      setNameError(validation.error ?? 'Invalid name');
      return;
    }
    if (restoring) return;

    setError(null);
    setStartedAt(Date.now());

    mutate({
      snapshot_name: snapshot,
      region,
      size,
      name,
    });
  };

  // Persist restore completion to Supabase when SSE reports done
  const [persisted, setPersisted] = useState(false);
  useEffect(() => {
    if (progress.status === 'completed' && progress.result && deploymentId && !persisted) {
      setPersisted(true);
      updateDeploymentAfterRestore({
        data: {
          deploymentId,
          hostname: (progress.result.hostname as string) || undefined,
          ip: (progress.result.ip as string) || undefined,
          deployId: (progress.result.deploy_id as string) || undefined,
        },
      }).catch(() => { /* non-fatal — deployment row still exists */ });
    }
  }, [progress.status, progress.result, deploymentId, persisted]);

  const isCompleted = progress.status === 'completed';
  const isValid = name && !nameError && snapshot && region && size;
  const hasError = error || mutationError;

  // Success state
  if (isCompleted && progress.result) {
    const hostname = progress.result.hostname as string | undefined;
    const ip = progress.result.ip as string | undefined;

    return (
      <div className="mx-auto max-w-lg px-4 py-10">
        <div className="rounded-lg border bg-card p-6 space-y-4">
          <h2 className="text-lg font-semibold text-green-700">
            Restore Complete
          </h2>
          <p className="text-sm text-muted-foreground">
            Your deployment has been restored successfully.
          </p>
          <div className="space-y-2 text-sm">
            {hostname && (
              <div className="flex justify-between">
                <span className="text-muted-foreground">Hostname</span>
                <span className="font-mono">{hostname}</span>
              </div>
            )}
            {ip && (
              <div className="flex justify-between">
                <span className="text-muted-foreground">IP Address</span>
                <span className="font-mono">{ip}</span>
              </div>
            )}
          </div>
          {deploymentId && (
            <Link
              to="/deployments/$deploymentId"
              params={{ deploymentId }}
              className="inline-block mt-2 text-sm font-medium text-primary hover:underline"
            >
              View deployment
            </Link>
          )}
        </div>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-lg px-4 py-10 space-y-8">
      <h1 className="text-2xl font-bold">Restore from Snapshot</h1>

      {/* Error banner */}
      {hasError && (
        <div className="rounded-md bg-red-50 border border-red-200 p-3 text-sm text-red-700">
          {error || mutationError}
        </div>
      )}

      {/* Snapshot select */}
      <div className="space-y-2">
        <Label>Snapshot</Label>
        {loadingSnapshots ? (
          <div className="space-y-2">
            <div className="h-10 rounded-md bg-muted animate-pulse" />
          </div>
        ) : snapshotError ? (
          <div className="rounded-md bg-red-50 border border-red-200 p-3 text-sm text-red-700">
            {snapshotError}
          </div>
        ) : snapshots.length === 0 ? (
          <p className="text-sm text-muted-foreground">
            No snapshots available. Create a snapshot from an existing
            deployment first.
          </p>
        ) : (
          <Select
            value={snapshot}
            onValueChange={handleSnapshotChange}
            disabled={restoring}
          >
            <SelectTrigger>
              <SelectValue placeholder="Select a snapshot" />
            </SelectTrigger>
            <SelectContent>
              {snapshots.map((s) => (
                <SelectItem key={s.snapshotName} value={s.snapshotName}>
                  {s.templateName} ({s.snapshotName})
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        )}
      </div>

      {/* Deployment Name */}
      <div className="space-y-2">
        <Label htmlFor="restore-name">Deployment Name</Label>
        {loadingSnapshots ? (
          <div className="h-10 rounded-md bg-muted animate-pulse" />
        ) : (
          <>
            <Input
              id="restore-name"
              placeholder="my-agent"
              value={name}
              onChange={(e) => handleNameChange(e.target.value)}
              onBlur={() => {
                const v = validateDeploymentName(name);
                setNameError(v.valid ? null : (v.error ?? 'Invalid'));
              }}
              disabled={restoring}
            />
            {nameError && (
              <p className="text-sm text-red-600">{nameError}</p>
            )}
            <p className="text-xs text-muted-foreground">
              Lowercase letters, numbers, and hyphens. 3-63 characters.
            </p>
          </>
        )}
      </div>

      {/* Region */}
      <div className="space-y-2">
        <Label>Region</Label>
        {loadingSnapshots ? (
          <div className="h-10 rounded-md bg-muted animate-pulse" />
        ) : (
          <Select value={region} onValueChange={setRegion} disabled={restoring}>
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {REGIONS.map((r) => (
                <SelectItem key={r} value={r}>
                  {REGION_LABELS[r] ?? r}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        )}
      </div>

      {/* Size */}
      <div className="space-y-2">
        <Label>Size</Label>
        {loadingSnapshots ? (
          <div className="h-10 rounded-md bg-muted animate-pulse" />
        ) : (
          <Select value={size} onValueChange={setSize} disabled={restoring}>
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {SIZES.map((s) => (
                <SelectItem key={s} value={s}>
                  {SIZE_LABELS[s] ?? s}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        )}
      </div>

      {/* Progress bar */}
      {progress.status !== 'idle' && (
        <OperationProgressBar
          progress={progress}
          startedAt={startedAt}
          onClose={resetMutation}
        />
      )}

      {/* Restore button */}
      <Button
        onClick={handleRestore}
        disabled={!isValid || restoring || snapshots.length === 0}
        className="w-full"
        size="lg"
      >
        {restoring ? 'Restoring...' : 'Restore Agent'}
      </Button>
    </div>
  );
}

function extractDigitalOceanSnapshot(
  template: AgentTemplate
): string | null {
  if (!template.provider_snapshots) return null;
  const doSnapshot = template.provider_snapshots['digitalocean'];
  return typeof doSnapshot === 'string' ? doSnapshot : null;
}
